import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProviders } from "@/components/auth/providers";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Power Landmark Holdin", 
  description: "Generated by create next app",
  other: {
    "referrer": "unsafe-url"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta name="referrer" content="unsafe-url" />
      </head>
      <body
        className={`${inter.className} antialiased`}
      >
        <AuthProviders>
          <CartProvider>
            {children}
            <Toaster position="top-right" />
          </CartProvider>
        </AuthProviders>
      </body>
    </html>
  );
}
